services:
  smib-slack:
    container_name: smib-slack
    build:
      context: .
      dockerfile: smib-fast.Dockerfile
    image: smib-slack
    depends_on:
      - smib-db
    environment:
      - WEBSERVER_HOST=smib-webserver
      - WEBSOCKET_ALLOWED_HOSTS=smib-webserver,smib-webserver
      - MONGO_DB_HOST=smib-db
    command: "python -m smib.slack"
    restart: unless-stopped

  smib-webserver:
    container_name: smib-webserver
    build:
      context: .
      dockerfile: smib-fast.Dockerfile
    image: smib-webserver
    ports:
      - "80:80"
    depends_on:
      - smib-slack
    environment:
      - WEBSOCKET_HOST=smib-slack
    command: "python -m smib.webserver"
    restart: unless-stopped

  smib-db:

    # Specific version - latest that works on a pi
    image: mongo:4.4.18
    container_name: smib-db
    restart: unless-stopped
    env_file:
      - path: .env
        required: false

  smib-db-ui:
    image: mongo-express
    container_name: smib-db-ui
    depends_on:
      - smib-db
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://smib-db:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_OPTIONS_READONLY: true

networks:
  default:
    name: smib-bridge-network
    driver: bridge
