[tool.poetry]
name = "smib"
version = "1.2.0"
description = ""
authors = ["sam57719 <sam57719@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-decouple = "^3.8"
slack-bolt = "^1.18.1"
python-dotenv = "^1.0.1"
flask = "^3.0.2"
simple-websocket-server = "^0.4.4"
websocket-client = "^1.7.0"
websockets = "^12.0"
tornado = "^6.4"
injectable = "^3.4.7"
apscheduler = "^3.10.4"
uvicorn = "^0.30.1"
dataclasses-json = "^0.6.4"
aiohttp = "^3.9.5"
pymongo = "^4.7.0"
mogo = "^0.6.0"
fastapi = "^0.111.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
